version: "3.8"

services:

  ollama_gpu:
    image: ollama/ollama:latest
    container_name: ollama-gpu
    ports:
      - "11434:11434"
    restart: always
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  ollama_cpu:
    image: ollama/ollama:latest
    container_name: ollama-cpu
    ports:
      - "11435:11434"
    restart: no
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: "local-dev-compose-net"
